### PR TITLE
Fashion variation

### PR DESCRIPTION
**Pull request by srgzlb**
Added Fashion variation
Since new variations were implemented the layout looked broken in some places because of other fonts, letter spacings, etc.

Changelog:

1. Added colors and settings of Fashion variation to settings_data
2. Compressed all images
3. Fixed background image width in Images section
4. Fixed text positioning in the Images section
5. Fixed search input field positioning
6. Cleaned up the code

### CODE REVIEW

**Comment by zmajstor** [comment]
There are a bunch of new files for the `romantic` variation as well in this PR ... is it intentional?

image

**Comment by srgzlb** [comment]
@zmajstor Yes, it is. I couldn't continue to work on the Fashion variation without changes I made to Romantic variation, so I was forced to merge `romantic` branch into `fashion` branch to get not stuck.
I just hurried to create this PR, I needed to merge the Romantic PR first to avoid confusion :)

**Comment by zmajstor** [comment]
> I just hurried to create this PR, I needed to merge the Romantic PR first to avoid confusion :)

Then, maybe you can consider changing the target branch of this PR?

image

**Comment by srgzlb** [comment]
@zmajstor No, it doesn't make sense
I have 2 PRs implementation of variations. I posted links in the Shop-team channel with a break of 1 day. So if you can check PR #80 first then I'll merge it, and the current PR won't have 'odd' files.

**Review by zmajstor — APPROVED** [review]

**Pull request merged**
